# loop logistics
epochs: 15
start_epoch: 0
print_freq: 10

# loss
contrast_type: "class_aware"
ce_type: "standard" # ["standard", "symmetric", "smoothed", "soft"]
alpha: 1.0
beta: 1.0
eta: 1.0

# algo-related stuff
aug_versions: "wss" # ["w", "ws", "wss", "ss"]
dist_type: "cosine" # ["cosine", "euclidean"]
ce_sup_type: "weak_strong" # ["weak_all", "weak_weak", "weak_strong", "self_all"]
refine_method: "nearest_neighbors"
num_neighbors: 10
queue_size: -1
epoch_labeling: false
